#!/bin/sh

displayJavaInstallMessage() {
	echo "$1 Please install Java 7 or Java 8 and ensure it's available on the path."
	echo "You can find more information about how to do this at <http://bladerunnerjs.org/docs/use/install/>."
	echo ""
	exit
}

if [ -z `which java` ]; then
	displayJavaInstallMessage "Java is either not installed on your computer or not available on the path."
fi

JAVA_VERSION=`java -version 2>&1 | head -1 | sed -r "s/^.*\"([^\"]+).*$/\1/"`
JAVA_VERSION_INT=`echo $JAVA_VERSION | sed -r "s/^([0-9]+)\.([0-9]+).*$/\1\2/"`

if [ $JAVA_VERSION_INT -le 16 ]; then
	displayJavaInstallMessage "Java $JAVA_VERSION is not new enough to run BladeRunnerJS."
fi

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
BRJS_CLASSPATH="$SCRIPT_DIR/libs/java/system/*:$SCRIPT_DIR/../conf/java/*"

java $JAVA_OPTS -cp "$BRJS_CLASSPATH" org.bladerunnerjs.runner.CommandRunner "$SCRIPT_DIR" "$@"
