"use strict";

var Errors = require('br/Errors');

/**
 * @name br.services.AppVersionService
 * @constructor
 * @class
 * @interface
 * This class provides access to the app version which is automatically generated by BladeRunnerJS
 */
function AppVersionService() {};

/**
 * Returns the app version
 */
AppVersionService.prototype.getVersion = function() {
	throw new Errors.UnimplementedInterfaceError("AppVersionService.getVersion() has not been implemented.");
};

module.exports = AppVersionService;
