"use strict";

/**
* @module br/services/AppVersionService
*/

var Errors = require('br/Errors');

/**
* An interface for classes that provides access to the app version
* which is automatically generated by BladeRunnerJS
* @class
* @interface
* @alias module:br/services/AppVersionService
*/
function AppVersionService() {};

/**
 * Returns the app version
 */
AppVersionService.prototype.getVersion = function() {
	throw new Errors.UnimplementedInterfaceError("AppVersionService.getVersion() has not been implemented.");
};

module.exports = AppVersionService;
