package org.bladerunnerjs.model;

import java.io.File;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import org.bladerunnerjs.model.engine.Node;
import org.bladerunnerjs.model.engine.NodeItem;
import org.bladerunnerjs.model.engine.RootNode;
import org.bladerunnerjs.plugin.AssetPlugin;

public abstract class AbstractAssetContainer extends AbstractBRJSNode implements AssetContainer {
	private final NodeItem<SourceAssetLocation> src = new NodeItem<>(SourceAssetLocation.class, "src");
	private final NodeItem<DeepAssetLocation> resources = new NodeItem<>(DeepAssetLocation.class, "resources");
	
	public AbstractAssetContainer(RootNode rootNode, File dir) {
		init(rootNode, rootNode, dir);
	}
	
	@Override
	public App getApp() {
		Node node = this.parentNode();
		
		while(!(node instanceof App)) {
			node = node.parentNode();
		}
		
		return (App) node;
	}
	
	@Override
	public String requirePrefix() {
		return "/" + namespace().replaceAll("\\.", "/");
	}
	
	@Override
	public List<SourceModule> sourceModules() {
		List<SourceModule> sourceModules = new ArrayList<SourceModule>();
			
		for(AssetPlugin assetPlugin : (root()).plugins().assetProducers()) {
			for (AssetLocation assetLocation : assetLocations())
			{
				sourceModules.addAll(assetPlugin.getSourceModules(assetLocation));
			}
		}
		
		return sourceModules;
	}
	
	@Override
	public SourceModule sourceModule(String requirePath) {
		for(SourceModule sourceModule : sourceModules()) {
			if(sourceModule.getRequirePath().equals(requirePath)) {
				return sourceModule;
			}
		}
		
		return null;
	}
	
	@Override
	public AssetLocation assetLocation(String locationPath) {
		// TODO: remove this temporary hack once asset locations are being generated by the asset plug-ins
		if(locationPath.equals("resources")) return resources();
		
		AssetLocation assetLocation = null;
		URI assetContainerUri = dir().toURI();
		
		for(AssetLocation nextAssetLocation : assetLocations()) {
			String nextLocationPath = assetContainerUri.relativize(nextAssetLocation.dir().toURI()).getPath().replaceAll("/$", "");
			
			if(nextLocationPath.equals(locationPath)) {
				assetLocation = nextAssetLocation;
				break;
			}
		}
		
		return assetLocation;
	}
	
	@Override
	public List<AssetLocation> assetLocations() {
		List<AssetLocation> assetLocations = new ArrayList<>();
		
		assetLocations.add(resources());
		assetLocations.add(src());
		assetLocations.addAll(src().getChildAssetLocations());
		
		return assetLocations;
	}
	
	// TODO: remove this method once asset locations are being generated by the asset plug-ins
	public SourceAssetLocation src() {
		return item(src);
	}
	
	// TODO: remove this method once asset locations are being generated by the asset plug-ins
	public AssetLocation resources()
	{
		return item(resources);
	}
}
