"use strict";

/**
* @module br/services/appversion/BRAppVersionService
*/

var br = require('br/Core');
var AppVersionService = require('br/services/AppVersionService');

/**
* This class provides access to the App version which is automatically generated by BladeRunnerJS
* @class
* @alias module:br/services/appversion/BRAppVersionService
* @implements module:br/services/AppVersionService
*/
function BRAppVersionService() {
};

BRAppVersionService.prototype.getVersion = function(bundlePath)	{
	return window.$BRJS_APP_VERSION;
}

br.implement(BRAppVersionService, AppVersionService);

module.exports = BRAppVersionService;
