package org.bladerunnerjs.appserver.filter;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.Writer;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.io.IOUtils;


@SuppressWarnings("serial")
public class DummyServlet extends HttpServlet
{
	private String responseText;
	private int responseCode;
	private String contentType;

	public DummyServlet()
	{
		resetResponse();
	}

	public void setResponseText(String responseText)
	{
		this.responseText = responseText;
	}

	public void setResponseCode(int responseCode)
	{
		this.responseCode = responseCode;
	}

	public void setContentType(String contentType)
	{
		this.contentType = contentType;
	}

	public void resetResponse()
	{
		responseText = "OK - This content was generated by "+this.getClass().getSimpleName();
		responseCode = 200;
		contentType = "text/plain";
	}

	@Override
	protected void doGet(final HttpServletRequest request, final HttpServletResponse response)
	{
		Writer out;
		try
		{
			response.setStatus(responseCode);
			if (request.getRequestURI().endsWith("br-logo.png")) {
				IOUtils.copy(new FileInputStream(new File("src/test/resources/br-logo.png")), response.getOutputStream());
				response.getOutputStream().flush();
			} else {
				response.setContentType(contentType);
				out = response.getWriter();
				out.write(responseText);				
				out.flush();
			}
		}
		catch (IOException ex)
		{
			throw new UnknownBundlerException(ex);
		}
	}

	
	public class UnknownBundlerException extends RuntimeException {

		private static final long serialVersionUID = 8855303440924373407L;
		
		public UnknownBundlerException(Exception e) {
			super(e);
		}

	}
}
