var Errors = require('br/Errors');

/**
 * @name br.services.AppVersionService
 * @constructor
 * @class
 * @interface
 * This class provides access to the App version which is automatically generated by BladeRunnerJS
 */
function AppVersionService() {};

/**
 * Returns the version for the App
 */
AppVersionService.prototype.getVersion = function()	{
	throw new Errors.UnimplementedInterfaceError("AppVersionService.getVersion() has not been implemented.");
};

/**
* Set the version for the App
*/
AppVersionService.prototype.setVersion = function(version)	{
	throw new Errors.UnimplementedInterfaceError("AppVersionService.setVersion() has not been implemented.");
};

module.exports = AppVersionService;
