"use strict";

var br = require('br/Core');
var Errors = require('br/Errors');
var AppVersionService = require('br/services/AppVersionService');

/**
 * @name br.services.AppVersionService
 * @constructor
 * @class This class provides access to the App version which is automatically generated by BladeRunnerJS
 *
 * @implements br.services.AppVersionService
 */
function BRAppVersionService() {
	this.version = "";
	this.versionSet = false;
};

BRAppVersionService.prototype.getVersion = function()	{
	if (!this.versionSet) {
		throw new Errors.IllegalStateError("AppVersion has not been set.");
	}
	return this.version;
}

BRAppVersionService.prototype.setVersion = function(version)	{
	if (this.versionSet) {
		throw new Errors.IllegalStateError("AppVersion has already been set.");
	}
	this.version = version;
	this.versionSet = true;
}

br.implement(BRAppVersionService, AppVersionService);

module.exports = BRAppVersionService;
