"use strict";

var br = require('br/Core');
var AppVersionService = require('br/services/AppVersionService');

/**
* @name br.services.BRAppVersionService
* @constructor
* @class This class provides access to the App version which is automatically generated by BladeRunnerJS
*
* @implements br.services.AppVersionService
*/
function BRAppVersionService() {
};

BRAppVersionService.prototype.getBundlePath = function(bundlePath)	{
	return window.$BRJS_APP_VERSION;
}

br.implement(BRAppVersionService, AppVersionService);

module.exports = BRAppVersionService;
