package com.caplin.cutlass.command.export;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.filefilter.AndFileFilter;
import org.apache.commons.io.filefilter.IOFileFilter;
import org.apache.commons.io.filefilter.NotFileFilter;
import org.apache.commons.io.filefilter.PrefixFileFilter;
import org.apache.commons.io.filefilter.SuffixFileFilter;

import com.caplin.cutlass.EncodingAccessor;

import org.bladerunnerjs.core.console.ConsoleWriter;
import org.bladerunnerjs.core.plugin.command.ArgsParsingCommandPlugin;
import org.bladerunnerjs.model.exception.command.CommandOperationException;
import org.bladerunnerjs.model.exception.command.CommandArgumentsException;
import org.bladerunnerjs.model.exception.command.NodeDoesNotExistException;
import com.caplin.cutlass.util.FileUtility;
import org.bladerunnerjs.model.App;
import org.bladerunnerjs.model.BRJS;
import org.bladerunnerjs.model.JsLib;

import com.caplin.cutlass.BRJSAccessor;

import com.caplin.cutlass.structure.AppStructureVerifier;
import com.martiansoftware.jsap.JSAP;
import com.martiansoftware.jsap.JSAPException;
import com.martiansoftware.jsap.JSAPResult;
import com.martiansoftware.jsap.UnflaggedOption;

public class ExportApplicationCommand extends ArgsParsingCommandPlugin
{
	private final static String DISCLAIMER = "Do not edit this file; edits will be lost after upgrades.";
	
	private BRJS brjs;
	private File sdkBaseDir;
	private ConsoleWriter out;
	
	public ExportApplicationCommand()
	{
	}
	
	@Override
	protected void configureArgsParser(JSAP argsParser) throws JSAPException {
		argsParser.registerParameter(new UnflaggedOption("app-name").setRequired(true).setHelp("the name of the application to be exported"));
		argsParser.registerParameter(new UnflaggedOption("disclaimer").setDefault(DISCLAIMER).setRequired(false).setHelp("a disclaimer that will be added to every exported class"));
	}
	
	@Override
	public void setBRJS(BRJS brjs)
	{
		this.brjs = brjs;
		sdkBaseDir = brjs.file("sdk");
		out = BRJSAccessor.root.getConsoleWriter();
	}
	
	@Override
	public String getCommandName()
	{
		return "export-app";
	}
	
	@Override
	public String getCommandDescription()
	{
		return "Create an importable zip for a given application";
	}
	
	@Override
	protected void doCommand(JSAPResult parsedArgs) throws CommandArgumentsException, CommandOperationException {
		String appName = parsedArgs.getString("app-name");
		String disclaimer = "/*\n* " + parsedArgs.getString("disclaimer") + "\n*/\n\n";
		App app = brjs.app(appName);
		
		if(!app.dirExists()) throw new NodeDoesNotExistException(app, this);
		
		File destinationZipLocation = brjs.file("sdk/" + appName + ".zip");
		
		try 
		{
			File existingAppDir = getApplicationDir(appName);
			
			File temporaryDirectoryForMotif = FileUtility.createTemporaryDirectoryWithSpecifiedFolderName(appName);			
			
			IOFileFilter excludeUserLibraryTestsFilter = createExcludeUserLibsTestsFilter(appName);
			IOFileFilter excludeDirFilter = new ExcludeDirFileFilter("js-test-driver", "bundles");
			IOFileFilter excludeJarFilter = new NotFileFilter(new AndFileFilter(new PrefixFileFilter("brjs-"),new SuffixFileFilter(".jar")));
			IOFileFilter filter = new AndFileFilter(excludeDirFilter, excludeJarFilter);
			filter = new AndFileFilter(filter, excludeUserLibraryTestsFilter);
			
			FileUtility.createResourcesFromSdkTemplate(existingAppDir, temporaryDirectoryForMotif, filter);
			includeDisclaimerInDirectoryClasses(new File(temporaryDirectoryForMotif, "libs"), disclaimer);
			FileUtility.zipFolder(temporaryDirectoryForMotif, destinationZipLocation, false);
		}
		catch (Exception e)
		{
			throw new CommandOperationException("Could not create application zip for application '" + appName + "'", e);  
		}

		out.println("Successfully exported application '" + appName + "'");
		out.println(" " + destinationZipLocation.getAbsolutePath());
	}
	
	private IOFileFilter createExcludeUserLibsTestsFilter(String appName) {
		IOFileFilter excludeDirFilter = new ExcludeDirFileFilter("");
		
		for (JsLib jsLib : BRJSAccessor.root.app(appName).jsLibs())
		{
			if (jsLib.parentNode() instanceof App)
			{
				excludeDirFilter = new AndFileFilter (excludeDirFilter, new ExcludeDirFileFilter(jsLib.getName(), "test"));
			}
		}
		
		return excludeDirFilter;
	}

	private File getApplicationDir(String appName) throws CommandArgumentsException 
	{
		File appDir = AppStructureVerifier.getApplicationDirFileObject(sdkBaseDir, appName);
		
		if(appDir.exists() == false)
		{
			throw new CommandArgumentsException("Could not find application '" + appName + "'", this);
		}
		
		return appDir;
	}
	
	private void includeDisclaimerInDirectoryClasses(File dir, String disclaimer) throws IOException {
		String[] extensions = {"js"};
		
		if (dir.exists())
		{
			for (File file : FileUtils.listFiles(dir, extensions, true))
			{
				includeDisclaimer(file, disclaimer);
			}
		}
	}

	private void includeDisclaimer(File file, String disclaimer) throws IOException {
		String fileContent = FileUtils.readFileToString(file, EncodingAccessor.getDefaultOutputEncoding());
	
		FileUtils.writeStringToFile(file, disclaimer + fileContent, EncodingAccessor.getDefaultOutputEncoding());
	}
}
